"""Compiling with the sopc binary, so served prompts match the CLI byte for byte.

Each call writes the files to a temp folder and runs `sopc validate --json`, then `sopc -o` or `sopc lint --json`;
`sopc export` reads files into the structured items the forms edit. The binary is `SOPC_BIN`, else `sopc` on PATH.
It needs the current format (agents compose blocks, no `locked`); `sopc migrate` converts a folder in an older one.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import threading
from collections import OrderedDict
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath

Files = dict[str, str]

BUILD_DIR = "build"
TIMEOUT = 60


class SopcUnavailable(RuntimeError):
    """The sopc binary is missing, too old, or failed unexpectedly."""


@dataclass(frozen=True)
class Issue:
    code: str
    message: str
    path: str
    severity: str
    # Filled in by forms.locate: the item and field the issue is about, and a plain-language message.
    kind: str | None = None
    id: str | None = None
    field: str | None = None
    index: int | None = None
    text: str | None = None

    def to_dict(self) -> dict:
        out = {"code": self.code, "message": self.message, "path": self.path, "severity": self.severity}
        if self.text is not None:
            out.update(kind=self.kind, id=self.id, field=self.field, index=self.index, text=self.text)
        return out


@dataclass
class Compiled:
    issues: list[Issue]
    lock: dict = field(default_factory=dict)
    agents: dict[str, dict] = field(default_factory=dict)  # id -> {platform_ref, hash, prompt, tools, sops, blocks}

    @property
    def valid(self) -> bool:
        return _ok(self.issues)


class Invalid(Exception):
    """Files that don't compile. Carries sopc's issues."""

    def __init__(self, issues: list[Issue]):
        super().__init__("; ".join(f"{i.path}: {i.message}" for i in issues))
        self.issues = issues


def path_issues(files: Files) -> list[Issue]:
    """Paths must be relative, inside the folder, and use `/`."""
    issues = []
    for path in files:
        if not is_safe_path(path):
            issues.append(Issue("unsafe_path", "paths must be relative to the sopc folder, use '/', and not contain '..'", path, "error"))
        elif path == BUILD_DIR or path.startswith(BUILD_DIR + "/"):
            issues.append(Issue("reserved_path", "build/ is generated by sopc; don't store it", path, "error"))
    return issues


def is_safe_path(path: str) -> bool:
    if not path or len(path) > 512 or "\\" in path or "\0" in path or path.startswith("/") or ":" in path.split("/")[0]:
        return False
    return all(part not in ("", ".", "..") for part in path.split("/"))


def without_build(files: Files) -> Files:
    """Whole-folder uploads may include a committed build/; it's regenerated, so drop it."""
    return {p: c for p, c in files.items() if not (p == BUILD_DIR or p.startswith(BUILD_DIR + "/"))}


class Sopc:
    def __init__(self, binary: str | None = None, cache_size: int = 32):
        self.binary = binary or os.environ.get("SOPC_BIN") or shutil.which("sopc")
        self._cache: OrderedDict[str, Compiled] = OrderedDict()
        self._cache_size = cache_size
        self._exports: OrderedDict[str, dict] = OrderedDict()
        self._lock = threading.Lock()

    def validate(self, files: Files) -> list[Issue]:
        return self.compile(files).issues

    def compile(self, files: Files) -> Compiled:
        """Validate, then build if valid. Results are cached by content."""
        key = _digest(files)
        with self._lock:
            if key in self._cache:
                self._cache.move_to_end(key)
                return self._cache[key]
        result = self._compile(files)
        with self._lock:
            self._cache[key] = result
            while len(self._cache) > self._cache_size:
                self._cache.popitem(last=False)
        return result

    def export(self, files: Files) -> dict:
        """Every block's parsed fields (`sopc export`). Raises Invalid if a file can't be read.
        Only parsing is checked; references between files are validate's business."""
        key = "export:" + _digest(files)
        with self._lock:
            if key in self._exports:
                self._exports.move_to_end(key)
                return self._exports[key]
        with self._written(files) as (root, bad):
            if bad:
                raise Invalid(bad)
            proc = self._run(root, "export", check=False)
        try:
            body = json.loads(proc.stdout)
        except ValueError:
            raise SopcUnavailable(
                f"`{self.binary} export` failed (exit {proc.returncode}): {proc.stderr.strip()[:500]}. "
                "sopserve needs a sopc with `export` (after v0.0.7); set SOPC_BIN to it."
            ) from None
        if proc.returncode != 0:
            raise Invalid([Issue(i["code"], i["message"], i["path"], i["severity"]) for i in body.get("issues", [])])
        with self._lock:
            self._exports[key] = body
            while len(self._exports) > self._cache_size * 4:
                self._exports.popitem(last=False)
        return body

    def migrate(self, files: Files) -> dict:
        """`sopc migrate --yes` on a copy of the files: {migrated, plan, files}. `migrated` is False if the
        files were already in the current format. It converts the v0.0.8 format and removes `locked` (v0.0.9). Raises Invalid if sopc can't convert them exactly."""
        key = "migrate:" + _digest(files)
        with self._lock:
            if key in self._exports:
                return self._exports[key]
        with self._written(files) as (root, bad):
            if bad:
                raise Invalid(bad)
            proc = self._run(root, "migrate", "--yes", check=False, merge_output=True)
            out = proc.stdout.strip()
            if proc.returncode != 0:
                issues = [Issue(m.group(1), m.group(2), "", "error") for m in re.finditer(r"error \[([a-z_]+)\] (.*)", out)]
                raise Invalid(issues or [Issue("migrate_failed", out[:1000] or "sopc migrate failed", "", "error")])
            if "already in the current format" in out:
                return {"migrated": False, "plan": "", "files": dict(files)}
            lines = [line for line in out.splitlines() if not line.startswith(("Wrote ", "Run `sopc`"))]
            plan = "\n".join(lines).replace("Migrating . to", "Migrating to", 1).replace(" no longer has from . (", " no longer has (", 1)
            migrated = {p.relative_to(root).as_posix(): p.read_bytes().decode() for p in sorted(root.rglob("*")) if p.is_file()}
            result = {"migrated": True, "plan": plan, "files": migrated}
        with self._lock:
            self._exports[key] = result
        return result

    def lint(self, files: Files) -> list[dict]:
        with self._prepared(files) as (root, issues):
            if not _ok(issues):
                raise Invalid(issues)
            return json.loads(self._run(root, "lint", "--json").stdout or "[]")

    def _compile(self, files: Files) -> Compiled:
        with self._prepared(files) as (root, issues):
            if not _ok(issues):
                return Compiled(issues)
            out = root / BUILD_DIR
            self._run(root, "-o", str(out))
            lock = json.loads((out / "lock.json").read_text())
            agents = {}
            for agent_id, entry in lock["agents"].items():
                tool = out / f"{agent_id}.tool.json"
                agents[agent_id] = {
                    "platform_ref": entry["platform_ref"],
                    "hash": entry["hash"],
                    "prompt": (out / f"{agent_id}.prompt.md").read_bytes().decode(),
                    "tools": entry.get("tools", []),
                    "sops": json.loads(tool.read_text()) if tool.exists() else {},
                    "blocks": entry["blocks"],
                }
            return Compiled(issues, lock, agents)

    @contextmanager
    def _written(self, files: Files) -> Iterator[tuple[Path, list[Issue]]]:
        """The files in a temp folder, or the path problems that kept them from being written."""
        with tempfile.TemporaryDirectory(prefix="sopserve-") as tmp:
            root = Path(tmp)
            bad = path_issues(files)
            if not bad:
                for path, content in files.items():
                    dest = root / PurePosixPath(path)
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    dest.write_bytes(content.encode())
            yield root, bad

    @contextmanager
    def _prepared(self, files: Files) -> Iterator[tuple[Path, list[Issue]]]:
        """Write the files to a temp folder and validate them there."""
        with self._written(files) as (root, bad):
            yield root, bad or self._validate_dir(root)

    def _validate_dir(self, root: Path) -> list[Issue]:
        proc = self._run(root, "validate", "--json", check=False)
        try:
            body = json.loads(proc.stdout)
            return [Issue(i["code"], i["message"], i["path"], i["severity"]) for i in body["issues"]]
        except (ValueError, KeyError, TypeError):
            raise SopcUnavailable(
                f"`{self.binary} validate --json` failed (exit {proc.returncode}): {proc.stderr.strip()[:500].rstrip(".")}. "
                "sopserve needs a sopc release with `validate --json` (after v0.0.7); set SOPC_BIN to it."
            ) from None

    def _run(self, root: Path, *args: str, check: bool = True, merge_output: bool = False) -> subprocess.CompletedProcess:
        if not self.binary:
            raise SopcUnavailable("sopc not found; install it or set SOPC_BIN")
        try:
            proc = subprocess.run(
                [self.binary, "-C", ".", *args],
                cwd=root,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT if merge_output else subprocess.PIPE,
                text=True,
                timeout=TIMEOUT,
                env={**os.environ, "NO_COLOR": "1"},
            )
        except (OSError, subprocess.TimeoutExpired) as e:
            raise SopcUnavailable(f"running sopc failed: {e}") from e
        if check and proc.returncode != 0:
            raise SopcUnavailable(f"sopc {' '.join(args)} failed (exit {proc.returncode}): {proc.stderr.strip()[:500]}")
        return proc


def _ok(issues: list[Issue]) -> bool:
    return not any(i.severity == "error" for i in issues)


def _digest(files: Files) -> str:
    return hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()
