"""Compiling with the sopc binary, so served prompts match the CLI byte for byte.

Each call writes the files to a temp folder and runs `sopc validate --json`, then `sopc -o` or `sopc lint --json`.
The binary is `SOPC_BIN`, else `sopc` on PATH. It needs `validate --json` (sopc after v0.0.7).
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import threading
from collections import OrderedDict
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath

Files = dict[str, str]

BUILD_DIR = "build"
TIMEOUT = 60


class SopcUnavailable(RuntimeError):
    """The sopc binary is missing, too old, or failed unexpectedly."""


@dataclass(frozen=True)
class Issue:
    code: str
    message: str
    path: str
    severity: str

    def to_dict(self) -> dict:
        return {"code": self.code, "message": self.message, "path": self.path, "severity": self.severity}


@dataclass
class Compiled:
    issues: list[Issue]
    lock: dict = field(default_factory=dict)
    agents: dict[str, dict] = field(default_factory=dict)  # id -> {platform_ref, hash, prompt, tools, sops, blocks}

    @property
    def valid(self) -> bool:
        return _ok(self.issues)


class Invalid(Exception):
    """Files that don't compile. Carries sopc's issues."""

    def __init__(self, issues: list[Issue]):
        super().__init__("; ".join(f"{i.path}: {i.message}" for i in issues))
        self.issues = issues


def path_issues(files: Files) -> list[Issue]:
    """Paths must be relative, inside the folder, and use `/`."""
    issues = []
    for path in files:
        if not is_safe_path(path):
            issues.append(Issue("unsafe_path", "paths must be relative to the sopc folder, use '/', and not contain '..'", path, "error"))
        elif path == BUILD_DIR or path.startswith(BUILD_DIR + "/"):
            issues.append(Issue("reserved_path", "build/ is generated by sopc; don't store it", path, "error"))
    return issues


def is_safe_path(path: str) -> bool:
    if not path or len(path) > 512 or "\\" in path or "\0" in path or path.startswith("/") or ":" in path.split("/")[0]:
        return False
    return all(part not in ("", ".", "..") for part in path.split("/"))


def without_build(files: Files) -> Files:
    """Whole-folder uploads may include a committed build/; it's regenerated, so drop it."""
    return {p: c for p, c in files.items() if not (p == BUILD_DIR or p.startswith(BUILD_DIR + "/"))}


class Sopc:
    def __init__(self, binary: str | None = None, cache_size: int = 32):
        self.binary = binary or os.environ.get("SOPC_BIN") or shutil.which("sopc")
        self._cache: OrderedDict[str, Compiled] = OrderedDict()
        self._cache_size = cache_size
        self._lock = threading.Lock()

    def validate(self, files: Files) -> list[Issue]:
        return self.compile(files).issues

    def compile(self, files: Files) -> Compiled:
        """Validate, then build if valid. Results are cached by content."""
        key = _digest(files)
        with self._lock:
            if key in self._cache:
                self._cache.move_to_end(key)
                return self._cache[key]
        result = self._compile(files)
        with self._lock:
            self._cache[key] = result
            while len(self._cache) > self._cache_size:
                self._cache.popitem(last=False)
        return result

    def lint(self, files: Files) -> list[dict]:
        with self._prepared(files) as (root, issues):
            if not _ok(issues):
                raise Invalid(issues)
            return json.loads(self._run(root, "lint", "--json").stdout or "[]")

    def _compile(self, files: Files) -> Compiled:
        with self._prepared(files) as (root, issues):
            if not _ok(issues):
                return Compiled(issues)
            out = root / BUILD_DIR
            self._run(root, "-o", str(out))
            lock = json.loads((out / "lock.json").read_text())
            agents = {}
            for agent_id, entry in lock["agents"].items():
                tool = out / f"{agent_id}.tool.json"
                agents[agent_id] = {
                    "platform_ref": entry["platform_ref"],
                    "hash": entry["hash"],
                    "prompt": (out / f"{agent_id}.prompt.md").read_bytes().decode(),
                    "tools": entry.get("tools", []),
                    "sops": json.loads(tool.read_text()) if tool.exists() else {},
                    "blocks": entry["blocks"],
                }
            return Compiled(issues, lock, agents)

    @contextmanager
    def _prepared(self, files: Files) -> Iterator[tuple[Path, list[Issue]]]:
        """Write the files to a temp folder and validate them there."""
        with tempfile.TemporaryDirectory(prefix="sopserve-") as tmp:
            root = Path(tmp)
            bad = path_issues(files)
            if bad:
                yield root, bad
                return
            for path, content in files.items():
                dest = root / PurePosixPath(path)
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(content.encode())
            yield root, self._validate_dir(root)

    def _validate_dir(self, root: Path) -> list[Issue]:
        proc = self._run(root, "validate", "--json", check=False)
        try:
            body = json.loads(proc.stdout)
            return [Issue(i["code"], i["message"], i["path"], i["severity"]) for i in body["issues"]]
        except (ValueError, KeyError, TypeError):
            raise SopcUnavailable(
                f"`{self.binary} validate --json` failed (exit {proc.returncode}): {proc.stderr.strip()[:500].rstrip(".")}. "
                "sopserve needs a sopc release with `validate --json` (after v0.0.7); set SOPC_BIN to it."
            ) from None

    def _run(self, root: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
        if not self.binary:
            raise SopcUnavailable("sopc not found; install it or set SOPC_BIN")
        try:
            proc = subprocess.run(
                [self.binary, "-C", str(root), *args],
                capture_output=True,
                text=True,
                timeout=TIMEOUT,
                env={**os.environ, "NO_COLOR": "1"},
            )
        except (OSError, subprocess.TimeoutExpired) as e:
            raise SopcUnavailable(f"running sopc failed: {e}") from e
        if check and proc.returncode != 0:
            raise SopcUnavailable(f"sopc {' '.join(args)} failed (exit {proc.returncode}): {proc.stderr.strip()[:500]}")
        return proc


def _ok(issues: list[Issue]) -> bool:
    return not any(i.severity == "error" for i in issues)


def _digest(files: Files) -> str:
    return hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()
